version: "3.9"
services:
  backend:
    image: '#image'
    container_name: ulutman1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      SPRING_PROFILES_ACTIVE: main
      SERVER_PORT: 443
      POSTGRES_DB: jdbc:postgresql://database:5432/postgres
      POSTGRES_USER: ulutmanuser
      POSTGRES_PASSWORD: ulutman2024
      FULLCHAINPEM: /certs/live/backend.ulutman.com/fullchain.pem
      PRIVKEYPEM: /certs/live/backend.ulutman.com/privkey.pem
    volumes:
      - certs:/certs
  database:
    image: postgres:15
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ulutmanuser
      POSTGRES_PASSWORD: ulutman2024
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
  certs:
    external: true

#version: "3.9"
#services:
#      backend:
#        image: '#image'
#        container_name: ulutman1
#        restart: always
#        ports:
#          - "80:8080"
#        environment:
#          SPRING_PROFILES_ACTIVE: main
#          SERVER_PORT: 8080
#          POSTGRES_DB: postgres
#          POSTGRES_USER: ulutmanuser
#          POSTGRES_PASSWORD: ulutman2024
#      database:
#        image: postgres:15
#        restart: always
#        container_name: database
#        ports:
#          - "5432:5432"
#        environment:
#          POSTGRES_USER: ulutmanuser
#          POSTGRES_PASSWORD: ulutman2024
#        volumes:
#          - db_data:/var/lib/postgresql/data
#    volumes:
#      db_data:
