name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy project to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 51.20.65.141
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "Dockerfile,docker-compose.yml,pom.xml,mvnw,.mvn,src"
          target: "/home/ubuntu/ulutman-main"

      - name: Restart Docker app on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 51.20.65.141
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          command_timeout: 30m
          script: |
            mkdir -p /home/ubuntu/ulutman-main
            cd /home/ubuntu/ulutman-main
            docker compose up -d --build
            docker ps
